### PR TITLE
Adding the Finished global / home page CSS, all is responsive now

### PR DESCRIPTION
**Pull request by iStyyx**
**(Done by Davy (from the liveshare of Morgane))**

### CODE REVIEW

**Review by Benjamin-51 — DISMISSED** [review]
Everything look fine and work well on my end.

**Review by RomainClair — CHANGES_REQUESTED** [review]
The style.css file is invalid according to W3C validator
And for your site to not depend on an external ressource (and therefore work in demos where the server is not connected to the internet) you should host your assets (fonts, lib, images, etc)

**Review by Benjamin-51 — APPROVED** [review]
Looks good to me.

**Review by RomainClair — APPROVED** [review]
Fonts license file are probably not necessary in the repository.
You could use woff2 & woff formats

**Pull request merged**
