### PR TITLE
Us6 admin panel

### PR DESCRIPTION
**Pull request by Benjamin-51**

### CODE REVIEW

**Review by MorganeL-pro — CHANGES_REQUESTED** [review]
Pbs with display (need to check the CSS)

**Review by MorganeL-pro — COMMENTED** [review]
Ok for me

**Review by MorganeL-pro — COMMENTED** [review]
ok

**Review by MorganeL-pro — DISMISSED** [review]

**Review by MorganeL-pro — APPROVED** [review]

**Review by iStyyx — APPROVED** [review]
All looks good for me !

**Pull request merged**
